### ISSUE TITLE
[Help needed] Broadcast Streams Cache Last Result

### ISSUE THREAD

**Issue by nikhilro** [dart-lang/async#115]
Hey Dart Async folks!

I was hoping to get your help on an issue I've been having with setting up Streams in my flutter project. 

## Description: 
There are 3 broadcast streams A, B and C at the top level. They are initialized at the start of the app connecting to 3 different Firestore collections for the User. 

Now, each of them is transformed in multiple ways. So, A might give rise to A.1 and A.2; similarly, for B and C. In the end, you could imagine a data flow graph where every node is a stream. Widgets mostly tap into the leaves of this graph but could also theoretically tap into the inner node. Now, the problem comes by the fact that broadcast streams don't "cache" the last result. Right now, on rebuild the StreamBuilder widgets end up empty since the stream "now" has no data. In this newly rebuilt StreamBuilder widget, if we change the data on Firebase, the top-level broadcast stream gets some new data that flows down the graph of transformation into the Widget finally showing expected data. If it's rebuilt, it loses that data since the stream is, once again, now, "empty".  What I would want is if the Widget listening into a stream using StreamBuilder is rebuilt (that is, it's a new listener), it gets the same data it had before the rebuild. This same data should come from the "latest" (last) data top-level broadcast streams have.

in case the terminology is new:
Collection = a list of documents, equivalent to a table in SQL
Document = the object in JSON form, equivalent to a row in SQL

## Ask:
* Lol, what do you suggest I do? 
 I could try to implement my own StreamController that does cache the last result? I'm imagining my problem seems common enough that there's some solution out there that I just can't seem to find.

Thanks for your help!

**Comment by natebosch** [comment]
Nothing like this exists in this package or any Dart team authored package today.

I could imagine an implementation of a special stream type, and potentially an extension on `Stream` to return one. Each new listener on a this stream would receive the most recently emitted event when it starts listening.

I do worry a little about having a class which `implements Stream` and has this different behavior, but I also don't think it would make sense to be a standalone type. @lrhn - what are your thoughts?

It might be as simple as

```dart
import 'dart:async';

class _ReplayLatestStream<T> extends StreamView<T> {
  T _latest;
  final Stream<T> _stream;

  _ReplayLatestStream(this._latest, this._stream) : super(_stream) {
    _stream.listen((e) {
      _latest = e;
    });
  }

  @override
  StreamSubscription<T> listen(void Function(T) onData,
      {Function onError, void Function() onDone, bool cancelOnError}) {
    Future(() {
      onData(_latest);
    });
    return _stream.listen(onData,
        onError: onError, onDone: onDone, cancelOnError: cancelOnError);
  }
}

extension ReplayLatest<T> on Stream<T> {
  Stream<T> replayLatest(T startWith) =>
      _ReplayLatestStream(startWith, isBroadcast ? this : asBroadcastStream());
}
```

**Comment by lrhn** [comment]
That approach might cause another event to be sent before `onData` is called, and it will fail if `onData` is `null`, and not be updated if `onData` is changed before the event is delivered. I fairly often find myself doing:
```dart
var sub = stream.listen(null);
sub.onData((v) { .... });
```

It's implementable, but not this easily, sadly.

I do have a plan for a stream implementation where each listen causes a callback with a new controller, so all listeners can be managed individually.

With such a multi-listener stream, you should be able to implement the requested behavior easily:

```dart
Stream<T> repeatLast<T extends Object>(Stream<T> source) {
  var listeners = <StreamControlller>{};
  T? last = null;
  bool done = false;
  source.listen((event) {
     last = event;
     for (var listener in [...listeners]) listener.add(event);
   }, onError: (Object e, StackTrace s) {
     for (var listener in [...listeners]) listener.addError(e, s);
   }, onDone: () {
      done = true;
      last = null;
      for (var listener in listeners) listener.close();
   });
  return Stream.multi((StreamController c)  {
    if (done) {
      c.close();
    } else {
      var lastEvent = last;
      if (lastEvent != null) c.add(lastEvent);
      listeners.add(c);
    }
    c.onCancel = () {
      listeners.remove(c);
    };
  });
}
```

I think I'll re-prioritize that implementation.

**Comment by nikhilro** [comment]
Thank you so much for answering @natebosch and @lrhn!

> There are 3 broadcast streams A, B and C at the top level. They are initialized at the start of the app connecting to 3 different Firestore collections for the User.

Since we didn't want to cook up a hacky solution, for now, we are just creating these top-level streams anew for every listener which is expensive and unnecessary (but still pretty clean). If you have a better temporary solution, I would love to use that. Other than that, I look forward to using your solution @lrhn 🙏 . Would you happen to have an ETA?

**Comment by lrhn** [comment]
The `Stream.multi` constructor has now landed, so you can do something like:
```dart
// Copyright 2020 Google LLC.
// SPDX-License-Identifier: BSD-3-Clause
Stream<T> repeatLast<T>(Stream<T> source) {
  List<MultiStreamController<T>> controllers = [];
  void forEachController(void action(MultiStreamController)) {
    var i = 0, j = 0;
    while (i < controllers.length) {
      var controller = controllers[i++];
      if (controller.hasListener) {
        action(controller);
        if (controller.hasListener) {
          controllers[j++] = controller;
        }
      }
    }
    if (j < controllers.length) controllers.length = j;
  }

  bool done = false; // Set to true when [source] closes.
  /*late*/ T mostRecent; // Most recent event value.
  bool hasMostRecent = false; // Whether mostRecent is available.

  StreamSubscription<T> /*?*/ sub;
  void ensureSubscribed() {
    sub ??= source.listen((value) {
      mostRecent = value;
      hasMostRecent = true;
      forEachController((c) {
        c.addSync(value);
      });
    }, onError: (e, s) {
      forEachController((c) {
        c.addErrorSync(e, s);
      });
    }, onDone: () {
      done = true;
      forEachController((c) {
        c.closeSync();
      });
    });
  }

  // Subscribe early if it's a broadcast stream.
  if (source.isBroadcast) ensureSubscribed();
  return Stream<T>.multi((controller) {
    if (hasMostRecent) controller.add(mostRecent /*as T*/);
    if (done) {
      controller.close();
      return;
    }
    controllers.add(controller);
    ensureSubscribed();
  }, isBroadcast: source.isBroadcast);
}
```

**Comment by nikhilro** [comment]
Thanks! found a workaround for the project that needed this. will keep in mind for the future. gonna close this issue and re-open if I run into any issues with your suggested approach in the future :)
