### ISSUE TITLE
Idea: FutureSwitch: switchMap for Futures

### ISSUE THREAD

**Issue by camsteffen** [dart-lang/async#136]
If often want the behavior of `switchMap`, but it isn't convenient to create a `Stream` to feed into it. Especially if there are multiple places in the code that produce an "input event". `CancellableOperation` is a close fit, but it doesn't have a convenient "switch" or mechanism.

Example use case:

```dart
final FutureSwitch dataSwitch = FutureSwitch();

// controls a "loading" indicator
bool get isLoading => dataSwitch.isPending;

Future onClickLoad(someInput) async {
  var future = fetchData(someInput);
  var data = await dataSwitch.switchTo(future, onCancel: () => print('cancelled'));
  showData(data);
}
```
Partial implementation:

```dart
class FutureSwitch {
  StreamSubscription _sub;
  void Function() _onCancel;

  Future<T> switchTo<T>(Future<T> future, {void onCancel()}) {
    cancel();
    _onCancel = onCancel;
    var completer = new Completer<T>();
    _sub = future.asStream().listen(completer.complete,
        onError: completer.completeError, onDone: () {
      _sub = null;
      _onCancel = null;
    });
    return completer.future;
  }

  void cancel() {
    if (_sub != null) {
      _sub.cancel();
      _sub = null;
      if (_onCancel != null) {
        _onCancel();
        _onCancel = null;
      }
    }
  }
}
```

**Comment by natebosch** [comment]
I don't think I understand the semantics you are hoping for.

If I use `var data = await dataSwitch.switchTo(future);`

And then before `future` completes, I call `dataSwitch.switchTo(someOtherFuture)` the idea is that the previous `await` would never complete?

If I'm correct, another way to think about this is, I think, as a container for a `CancelableOperation` which cancels it's previous operation when the next one is put in:

```dart
class ReplaceableOperation<T> {
  CancelableOperation<T> _operation;

  Future<T> replace(Future<T> future) {
    _operation?.cancel();
   _operation = CancelableOperation.fromFuture(future);
  }

  void cancel() {
    _operation.cancel();
  }
}
```

Do I have the correct understanding? Can you describe a concrete use case? I'm having a hard time understanding when that might be useful.

**Comment by camsteffen** [comment]
Sorry I wasn't very clear. Yes your description is exactly correct.

A use case could be a master-detail interface. Every time the user selects an item, you have to fetch, process and display data in the detail view. The user may select a different item while the previously selected item is still loading. And this cancels the previous item from loading.

So imagine the detail view has a `setItemId` method...

```dart
setItemId(id) async {
  var data = await futureSwitch.switchTo(fetchData(id));
  // handle data, unless setItemId was called again
}
```
Here is how I would do the same with `switchMap`:

```dart
StreamController idController = new StreamController();

setItemId(id) {
  idController.add(id);
}

init() {
  idController.stream
      .switchMap((id) => fetchData(id).asStream())
      .listen((data) {
        // handle data...
      });
}
```

Maybe the comparison to `switchMap` is not very good?

So, kind of like what you said, the `FutureSwitch` is a holder for a `Future`. When a new `Future` is added, the previously added `Future` is "cancelled" (even though `Future`s can not be cancelled strictly speaking). `CancelableOperation` is a good comparison, but ultimately I think it is a different abstraction. Your `ReplaceableOperation<T>` is good, except I think it might be better to leave the type parameter on the method rather than the class. Imagine the view from before handles two types of data, but still can only show one item at a time.

```dart
FutureSwitch dataSwitch = new FutureSwitch()

loadFoo(id) async {
  Foo foo = await dataSwitch.switchTo(fetchFoo(id));
  // handle foo, unless loadFoo or loadBar was called again
}

loadBar(id) async {
  Bar bar = await dataSwitch.switchTo(fetchBar(id));
  // handle bar, unless loadFoo or loadBar was called again
}
```

And to extend that example, suppose that loading a Foo involves doing multiple asynchronous options one after another. So it may be interrupted at any point. And at this point, `CancelableOperation` or `switchMap` don't seem like a viable alternative anymore.

```dart
loadFoo(id) async {
  var foo = await dataSwitch.switchTo(fetchFoo(id));
  var details = await dataSwitch.switchTo(fetchFooDetails(foo));
  // handle data...
}
```

**Comment by natebosch** [comment]
> And to extend that example, suppose that loading a Foo involves doing multiple asynchronous options one after another. So it may be interrupted at any point. And at this point, `CancelableOperation` or `switchMap` don't seem like a viable alternative anymore.

Does it help to model those steps as chains of `.then` calls on the `CancelableOperation`?
https://pub.dev/documentation/async/latest/async/CancelableOperation/then.html

Overall since `Future` isn't decided for cancellation I think it's going to be tough to do much better here.

I think the `ReplaceableOperation` concept is likely easy enough to implement locally, and likely has details that are going to be specific enough to each use case that it's going to be hard to fit into a very wide reaching general purpose package like this. That is, I think it's closer to a business logic goal than a building block. I don't think it's a very good fit for this package. This might be something you want to publish in another package.

**Comment by lrhn** [comment]
If we don't care about cancelling, it's a fairly easy thing to do:
```dart
class FutureSwitch<T> {
  int _counter = 1;
  int _current = 0;
  Future<T> switchTo(Future<T> newFuture) {
    var id = _counter++;
    _current = id;
    var completer = Completer<T>();
    newFuture.then((data) {
      if (_current == id) completer.complete(data);
    }, onError: (Object error, StackTrace stack) {
      if (_current == id) completer.completeError(error, stack);
    });
    return completer.future;
  }
}
```

It's fairly specific, so I'm not sure it's something we'll want in `package:async`.

**Comment by camsteffen** [comment]
> Does it help to model those steps as chains of `.then` calls on the `CancelableOperation`?

That is quite a bit more awkward.

```dart
loadFoo(id) async {
  Foo foo;
  co = CancelableOperation.fromFuture(fetchFoo(id))
    .then((f) {
      foo = f;
      return fetchFooDetails(f);
    });
  var details = await co.value;
  // handle data...
}
```

@lrhn I used Stream subscriptions and cancelling in my example implementation because I thought it would have better implications for garbage collection. But I could be wrong. Otherwise, you can still add `cancel()` with a similar approach.

```dart
class FutureSwitch {
  int _counter = 0;
  Future<T> switchTo<T>(Future<T> newFuture) {
    var id = ++_counter;
    var completer = Completer<T>();
    newFuture.then((data) {
      if (_counter == id) completer.complete(data);
    }, onError: (Object error, StackTrace stack) {
      if (_counter == id) completer.completeError(error, stack);
    });
    return completer.future;
  }
  void cancel() => _counter++;
}
```

To try and put it in general "building block" terms, a `FutureSwitch` is like a swimlane. It allows only one asynchronous task to be in progress at a time. I think that this class would quite often be a cleaner abstraction than `CancelableOperation` since it doesn't require re-assignment and it works better with async/await syntax. The main problem in my opinion is that it is not as intuitive, and that is certainly not a minor problem. But it may be remedied by thinking of a better name for the class and/or the methods.
