### ISSUE TITLE
FR: DebounceStreamTransformer

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/async#14]
There are probably a dozen or so implementations of this internally today, most like:

```dart
stream.transform(new DebounceStreamTransformer(...))
```

or

```dart
stream.transform(debounce())
```

The primary needs seem to be specifying a duration in which no other event on the stream should have been added - I don't see too many other patterns. We could also make a `Debouncer` class so users that don't use `Stream` still would get a benefit.

**Comment by nex3** [comment]
This and #15 are covered by [this CL](https://codereview.chromium.org/1648963002/) by @lrhn. I think it's just waiting on him to iterate on it.

**Comment by matanlurey** [comment]
Would be nice to get some traction here, code duplication is suffering internally as a result.

**Comment by matanlurey** [comment]
Closed by https://github.com/dart-lang/stream_transform/pull/3.
