### ISSUE TITLE
CancelableOperation should not cause deadlocks

### ISSUE THREAD

**Issue by nt4f04uNd** [dart-lang/async#163]
i think the fact that something like that is possible is severely dangerous

API should be changed in some way to prevent this

```dart
Future<void> main() async {
  final completer = CancelableCompleter();
  Future.delayed(const Duration(seconds: 2), () {
    completer.operation.cancel();
  });
  Future.delayed(const Duration(seconds: 4), () {
    // makes no effect
    completer.complete('some value');
  });
  print('init');
  final cancel = await completer.operation.valueOrCancellation();
  print(cancel);
  final value = await completer.operation.value;
  // these lines are never reached
  print(value);
  print('end');
}
```

**Comment by natebosch** [comment]
The API is _intended_ to have `operation.value` never complete when the operation is canceled.

Our choices are either to have `value` never complete, or to complete as an error with something liked a `CanceledException`. The `valueOrCancellation()` API is the correct API to use if you want to avoid the Future that may never complete.

**Comment by nt4f04uNd** [comment]
What is the lifecycle of `then`s on such never completed futures? Can they be GC'ed at some point or do they live forever waiting that the future completes?

**Comment by natebosch** [comment]
> What is the lifecycle of `then`s on such never completed futures? Can they be GC'ed at some point or do they live forever waiting that the future completes?

The callback can be collected as long as the future instance can be collected. That is to say - a future that never completes is not _necessarily_ going to cause any memory leak. If you are concerned about a particular use of a future leaking you can use devtools to investigate the heap. https://flutter.dev/docs/development/tools/devtools/memory
