### ISSUE TITLE
Doc links don't work

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/async#168]
In the package page (https://pub.dev/packages/async), the API doc homepage (https://pub.dev/documentation/async/latest/), and the repo homepage (https://github.com/dart-lang/async#readme), links to the generated API doc don't work.

They go to URLs like this:
https://pub.dev/documentation/async/latest/async/AsyncCache-class.html

But the published doc's URLs are like this:
https://pub.dev/documentation/async/latest/pkg.async/AsyncCache-class.html

Which makes me wonder: did you really mean to change the library name from **async** to **pkg.async**? If so, editing the README is all that's necessary to fix this. If not...

**Comment by jonasfj** [comment]
This has already been fixed in https://github.com/dart-lang/async/pull/158, I think we just need to publish.

**Comment by jonasfj** [comment]
@natebosch, I think 376c0fe95fa6fe7a5a6c41ef7b4585085c826f89 has rolling into the SDK and google3, are we good to publish it now?

**Comment by natebosch** [comment]
@jonasfj - I think it is worth exploring the idea proposed in https://github.com/dart-lang/async/pull/161#issuecomment-822894833 first

**Comment by jayoung-lee** [comment]
@jonasfj Is this a major change? Then I think I can remove the part in the https://github.com/dart-lang/site-www/pull/3147 that refers to the async package and update it later.

**Comment by jonasfj** [comment]
@natebosch, I think there are [many reasons](https://github.com/dart-lang/async/pull/161#issuecomment-827424212) we shouldn't pursue `ChunkedStreamReader` as an extension on `StreamQueue`, can we publish this?

**Comment by natebosch** [comment]
Yeah I think we can keep the reader as is. We have a few other PRs to get rolled in and then I'll publish.

**Comment by kwalrath** [comment]
Looks like the links are working now. 🎉
