### ISSUE TITLE
ChunkedStreamReader is slow with large chunks

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/async#181]
If the stream consists of one large chunk, then these two lines are slow:
https://github.com/dart-lang/async/blob/f1c8882c927af68df6786124c94e857de0fa22c1/lib/src/chunked_stream_reader.dart#L112-L113

We can probably shave off the last one by tracking an offset in the buffer.. But to make the second fast we'll need a ListView of sorts, or possibly have to specialize to handle `Uint8List` in a special fast-path where we can create a view.

**Comment by jonasfj** [comment]
Context: https://github.com/simolus3/tar/issues/14

**Comment by simolus3** [comment]
For large buffers I would expect the second line to be much more expensive as `_buffer.length` is likely much larger than `size`.
Still, I'd love something that doesn't copy, even if it's just for `Uint8List` (which is probably the most common usage of chunked streams either way).

**Comment by jonasfj** [comment]
We could do: https://github.com/dart-lang/async/pull/182

We could even create a generic `ListView<T>(List<T> underlying, int start, int end)`, but even if we did that, we should prefer to use `Uint8List` in cases where we're splitting a `Uint8List`.

Note: this issue only really affects very very very large chunks. In https://github.com/simolus3/tar/issues/14 it's the case that after decompression we have a stream consisting of a single 673MB chunk, from which we want to read blocks of 512 bytes and lots of small files maybe 1-2kb :see_no_evil: 

In any case, I tested https://github.com/dart-lang/async/pull/182 against https://github.com/simolus3/tar/issues/14 locally, and it's fast again :D
