### ISSUE TITLE
how to upgrade async package? I can't upgrade because it's direct dependencies

### ISSUE THREAD

**Issue by alpcanm** [dart-lang/async#187]
I'm using version 2,6,1 i cant upgrade to 2,7,0 how can ı do this ?

**Comment by doradsoft** [comment]
Reproduced in my case also:

> Because every version of flutter_test from sdk depends on async 2.6.1 and <MY_APP> depends on async ^2.7.0, flutter_test from sdk is forbidden.
> So, because <MY_APP> depends on flutter_test any from sdk, version solving failed.
> pub get failed (1; So, because <MY_APP> depends on flutter_test any from sdk, version solving failed.)

Flutter 2.2.3
Dart 2.13.4

**Comment by alpcanm** [comment]
i still can't figure it out

**Comment by natebosch** [comment]
`flutter` and `flutter_test` pin some of their dependencies and you won't be able to resolve a different version of those packages without changing your version of the flutter SDK. I've filed a request to document this (or document it in a more discoverable place) at https://github.com/flutter/website/issues/6162
