### ISSUE TITLE
Feature request: Lazily check if any Future in a collection matches a given test

### ISSUE THREAD

**Issue by doppio** [dart-lang/async#199]
There've been times when I've wished I could test a collection of Futures to see if any of their return values match some test.  `Future.any` comes closest by returning as soon as any of the Futures completes, but I'd like to provide a collection of Futures that are expected to complete, and test their value. The idea would be to return as soon as one of the Futures completes with a desired value, without executing them one at a time or waiting for all of them to complete.

Example use case:
```dart
Future<bool> anyFutureIsZero(List<Future<int>> someIntFutures) {
  return Future.anyWhere(someIntFutures, (value) => value == 0);
}
```

Here's an (untested) implementation that I modified from `Future.any` to further illustrate the idea:
```dart
import 'dart:async';

static Future<bool> anyWhere<T>(
  Iterable<Future<T>> futures,
  bool Function(T) test,
) {
  final completer = Completer<bool>.sync();
  var numFuturesCompleted = 0;

  void onValue(T value) {
    if (completer.isCompleted) return;

    if (test(value)) {
      completer.complete(true);
    } else {
      numFuturesCompleted++;

      if (numFuturesCompleted == futures.length) {
        // All futures have completed without the test being satisfied.
        completer.complete(false);
      }
    }
  }

  void onError(Object error, StackTrace stack) {
    if (!completer.isCompleted) completer.completeError(error, stack);
  }

  for (final future in futures) {
    future.then(onValue, onError: onError);
  }

  return completer.future;
}
```

In the same vein, it could be useful to have a `firstWhere` function which returns the value that satisfied the test:
`Future<T> firstWhere(Iterable<Future<T>>, bool Function(T) test, {T orElse()?})`.

I'd be happy to submit a pull request if others feel this is useful. If this doesn't seem suitable to be built into this package, let me know and I can publish this as a separate package.

**Comment by mat100payette** [comment]
Would this be fine ?

```dart
Future<bool> anyWhere<T>(Iterable<Future<T>> futures, bool Function(T) test) {
  bool result = false;

  final Future<dynamic> action =
      Future.forEach(futures, (Future<T> future) async {
    if (result) {
      future.ignore();
    } else {
      result = await future.then(test);
    }
  });

  return action.then((dynamic _) => result);
}
```
You can use it this way:
```dart
final List<Future<int>> testFuturesTrue = <Future<int>>[
  Future<int>.value(1),
  Future<int>.value(0),
  Future<int>.value(2),
];

final List<Future<int>> testFuturesFalse = <Future<int>>[
  Future<int>.value(3),
  Future<int>.value(6),
  Future<int>.value(1),
];

final bool Function(int) isZeroTest = (int i) => i == 0;

final bool resultTrue = await anyWhere(testFuturesTrue , isZeroTest);
final bool resultFalse = await anyWhere(testFuturesFalse , isZeroTest);

print(testFuturesTrue);
print(testFuturesFalse);
```
Which prints:
> \> true
> \> false

**Comment by doppio** [comment]
@mat100payette, `Future.forEach` will wait for each future to complete, one at a time. The idea here is that all of the futures should be executed in parallel -- like `Future.wait` but with an "early out" as soon as the desired condition is met. If you imagine each of the futures was something more time-consuming like a web request, it could make a big difference.

**Comment by mat100payette** [comment]
> 
> 
> @mat100payette, `Future.forEach` will wait for each future to complete, one at a time. The idea here is that all of the futures should be executed in parallel -- like `Future.wait` but with an "early out" as soon as the desired condition is met. If you imagine each of the futures was something more time-consuming like a web request, it could make a big difference.

Sorry if I'm missing something, but where does `forEach` wait for the futures to complete ?

```dart
static Future forEach<T>(Iterable<T> elements, FutureOr action(T element)) {
  var iterator = elements.iterator;
  return doWhile(() {
    if (!iterator.moveNext()) return false;
    var result = action(iterator.current);
    if (result is Future) return result.then(_kTrue);
    return true;
  });
}
```
My callback is maybe wrong though, but your statement is false I believe.

**Comment by doppio** [comment]
The documentation says:
>If the call to action returns a Future<T>, the iteration waits until the future is completed before continuing with the next element.

It's in the implementation of `doWhile`:
```dart
if (result is Future<bool>) {
  result.then(nextIteration, onError: doneSignal._completeError);
  return;
}
```
The next iteration is only called when the previous one completes.

**Comment by lrhn** [comment]
It's a very specialized operation. I'd probably just do `Stream.fromFutures(futures).any(test)`, or `Stream.fromFutures(futures).firstWhere(test)` if you want the result.

If you have a collection of futures, and want to look at the results in the order they complete, use `Stream.fromFutures`. Streams are the canonical way to handle *multiple* asynchronous results arriving when they are ready.

**Comment by doppio** [comment]
That makes sense, thanks @lrhn.
