### ISSUE TITLE
Possible memory leaks?

### ISSUE THREAD

**Issue by maRci002** [dart-lang/async#200]
If the operation was canceled before it completes then [operation.value](https://github.com/dart-lang/async/blob/2.8.1/lib/src/cancelable_operation.dart#L43) will never complete so the resgistered callbacks / error callbacks will just hang in memory and if they reference some huge objects then they also won't be garbage collected.

```dart
  var opration = CancelableOperation.fromFuture(
    Future(() => 1),
    onCancel: () => print('onCancel'),
  );

  Future.sync(() => opration.cancel());

  opration.value.then((value) {
    // Holding some reference to Huge object
  }, onError: (e, s) {
    // Holding some reference to Huge object
  });

  opration.value.whenComplete(() {
    // Holding some reference to Huge object
  });

  opration.asStream().listen(
    (event) {
      // Holding some reference to Huge object
    },
    onDone: () => {
      // Holding some reference to Huge object
    },
  );
```

You might suggest I should use [valueOrCancellation](https://github.com/dart-lang/async/blob/2.8.1/lib/src/cancelable_operation.dart#L69) however it also registers some [callback functions](https://github.com/dart-lang/async/blob/2.8.1/lib/src/cancelable_operation.dart#L71-L72) which will stay alive since [value won't be completed](https://github.com/dart-lang/async/blob/2.8.1/lib/src/cancelable_operation.dart#L207-L213).

`asStream` also registers some [callback functions](https://github.com/dart-lang/async/blob/2.8.1/lib/src/cancelable_operation.dart#L53-L59).

**Comment by maRci002** [comment]
If the above is problem then this might be a solution for `valueOrCancellation` if we store the original `Future` (I know it should be `FutureOr` but made it simpler for the example solution)

```dart
  Future<T> get _originalFuture => _completer._originalFuture;

  Future<T?> valueOrCancellation([T? cancellationValue]) {
    var completer = Completer<T?>.sync();
    _originalFuture.then(
      (result) {
        if (!isCanceled) {
          completer.complete(result); // wasn't completed by cancel
        }
      },
      onError: (Object e, StackTrace? s) {
        if (!isCanceled) {
          completer.completeError(e, s); // wasn't completed by cancel
        }
      },
    );

    _completer._cancelMemo.future.then((_) {
      completer.complete(cancellationValue);
    }, onError: completer.completeError);

    return completer.future;
  }
```

**Comment by lrhn** [comment]
It's not easy to avoid hanging on to callbacks of futures, because there is no way to unsubscribe after adding the listeners.
The one thing we can do is to throw away the completer entirely when we know we won't need it.
Which might just be possible.
