### ISSUE TITLE
Stream.where but depending the previous value

### ISSUE THREAD

**Issue by woprandi** [dart-lang/async#201]
An interesting feature would be to allow to have a method like `where()` on Stream but with the previous value as parameter, allowing to filter the current value depending the previous one. Currently this feature seems to not exist. With the standard library, you could derive the [`distinct`](https://api.flutter.dev/flutter/dart-async/Stream/distinct.html) method since you can pass a function with previous and current as parameters  but :

1. It is not designed for this use-case (the name is clear)
2. I don't know if the parameters order is guarantee despite the method signature suggests that yes. Since it does not matter for a equals comparison

**Comment by natebosch** [comment]
This feels pretty specialized to me - I'd recommend dropping an implementation near where you need it. It feels likely that the semantics you'd want could change by use case (semantics like whether the first event comes through, despite having no previous event to check against the condition), and trying to write something general enough to cover all desired semantics would carry a high cost in terms of the surface area of the library.

Something like this should get you started:

```dart
extension WherePrevious<T> on Stream<T> {
  /// Like [where] but the `test` receives the prior event in the stream instead
  /// of the current event.
  ///
  /// The first event of the stream is never emitted.
  ///
  /// For example, to emit all numbers which follow an odd:
  /// ```
  /// var afterOdd = numbers.wherePrivous((n) => n.isOdd);
  //  // if `numbers` emits `[1, 3, 2, 4]` then `afterOdd` emits `[3, 2]`
  /// ```
  ///
  /// Errors are forwarded directly.
  Stream<T> wherePrevious(bool Function(T previous) test) {
    bool havePrevious = false;
    late T previous;
    return transform(StreamTransformer.fromHandlers(handleData: (event, sink) {
      if (havePrevious && test(previous)) sink.add(event);
      havePrevious = true;
      previous = event;
    }));
  }
}
```
