### ISSUE TITLE
Change the default of `propagateCancel` argument in CancelableOperation.then

### ISSUE THREAD

**Issue by natebosch** [dart-lang/async#212]
See discussion in https://github.com/dart-lang/async/pull/211#discussion_r829662531

I haven't been able to find any tests that fail when I change the default, but it's hard to say for sure if there could be untested behavior.

I'm fairly confident that some of the usage I saw which does not pass the argument would expect cancellation to propagate.

cc @TastyPi - do you recall why you chose not propagating as the default? Do you have any use cases where propagating the cancel would result in incorrect behavior?

cc @lrhn @devoncarew - I'm tempted to try to roll out a change in the default as a minor release. I'm concerned that the unsafe default is going to cause more pain than potentially breaking an existing usage. WDYT?

**Comment by devoncarew** [comment]
This looks like the only use of `CancelableOperation` in flutter: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/test/flutter_web_platform.dart#L778. It doesn't look like there's a dep on `CancelableOperation.then`.

I'm guessing that what we're trying to do here is less about determining whether we should release a breaking change, and more about figuring out whether this is actually breaking (no real uses, nobody relying on the current behavior, ...).

**Comment by TastyPi** [comment]
The original issue is #80, #81 was a first version which has some possibly relevant discussion, and #83 is the final pull request. There may have been a discussion internal to Google, but I don't work there anymore so can't check.

The use case for not propagating is if you want to chain multiple `then` calls off the same operation, and you don't want to cancel everything if you cancel one chain.
