### ISSUE TITLE
Consider to make second invocation of `streamQueue.hasNext` be postponed concluding the result until the first invocation of `q.next` , unless the stream is closed.

### ISSUE THREAD

**Issue by Cat-sushi** [dart-lang/async#221]
First of all. it is very unintuitive that `await q.next` just after `await q.hasNext` returning `true` might fail.

2nd, there is no way to safely consume events in a `StreamQueue` one by one without additional useless `List` from `await q.take(1)`.

3rd, in case of `sc = StreamController(); q = StreamQueue(sc.stream)`, `sc.add(e)` awakes only one caller of `await q.hasNext` and the succeeding `await q.next` always succeeds. It is inconsistent with `q = StreamQueue(Stream.fromIterable(list))`

Finally, it is a breaking chang unintentionally introduced by the reimplementation of async in SDK 2.18, I guess.

A possible solution I think is that the second `q.hasNext` should proactively enter the event loop, even if the stream already has a event.

See dart-lang/sdk#50217 and #220, as well.

**Comment by Cat-sushi** [comment]
```dart
  q.hasNext.then((n) {
    print("4: $n");
  });
```
`4: false`
Who can understand such insane behavior!

**Comment by lrhn** [comment]
That `hasNext` evaluates to `false` after the previously enqueued `next` request has consumed the only event of the source stream, so the `hasNext` sees the stream close? Seems sane to me.

The class may need better documentation, but the underlying model is actually simple and predictable.

**Comment by Cat-sushi** [comment]
I myself understand the behavior, but I think almost nobody can understand such behavior.

**Comment by Cat-sushi** [comment]
Sorry, I mistakenly said `d: false` is insane.
I know `hasNext` usually return `false`.
My point was that, `await q.nest;` just after `await q.hasNext` returning `true` always succeeds, when `sc = StreamController(); q = StreamQueue(sc.stream)`.

**Comment by lrhn** [comment]
Not planning any change here.
Requests are enqueued. The only safe way to change the current behavior is to disallow queuing new requests while an existing request is being processed. Basically, it'd stop being a queue.

That's a different class, which can also exist (or can be implemented as a wrapper around the normal `StreamQueue`), but it's not something we'll change the existing class to.
