### ISSUE TITLE
async 1.13.0 breaks tour of heroes

### ISSUE THREAD

**Issue by alanhumphrey** [dart-lang/async#25]
I'm trying to run Tour of Heroes with async version 1.13.0 and I'm getting this error when the app tries to load in dartium:

    'package:async/src/byte_collector.dart': error: line 42 pos 16: generic functions not supported
    T _collectBytes<T>(
               ^: package:async/src/byte_collector.dart

Going back to version 1.12.0 allows the app to run.

**Comment by nex3** [comment]
I don't know what Tour of Heroes is, but it sounds like you're using a Dart version older than 1.21.0—the first version that supported real generic method syntax. This package's [SDK constraint](https://github.com/dart-lang/async/blob/master/pubspec.yaml#L13) declares a minimum version of 1.21.0, so something about your setup is busted.
