### ISSUE TITLE
Add a "backoff" Stream, i.e. one that fires less and less

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/async#34]
## API

Based slightly on https://www.npmjs.com/package/observable-backoff.

```dart
/// Returns a stream that emits the value returned by [action].
///
/// If the new value equals the previous, [ease] is used to lengthen the delay until [action] is
/// called again, up to a total of times specified by [retries].
Stream<T> backoff(FutureOr<T> action(), {
  Equality equality,
  double ease(double input),
  int retries,
}) => ...
```

---

Not ready to commit to a specific implementation/API yet, just through up here for discussion.

**Comment by nex3** [comment]
Can you provide some details about why/how this would be useful? I'm not very familiar with the RxJS/Observable context.

**Comment by matanlurey** [comment]
Sure! One (naive) reason would be polling a server or file for changes. Imagine the following:

_Ignore the fact that HTTP headers could help with this problem or long-polling._

```dart
Stream<String> pollTextFile(Uri uri) => ...

main() {
  pollTextFile(Uri.parse('/status.txt')).distinct().listen(print);
}
```

In ~1 line of code (yay Dart!) we can now write something that prints to the console whenever `/status.txt` changes. However, if this file is on some-sort of bandwidth constrained server (imagine where you pay $ per KB), you're going to have a bad time. Even though the `print` only happens when the file changes, you check every-time for changes.

Backoff, or exponential or eased backoff implies works based on the strategy that if a value `T` hasn't change since last check, we should assume it's even _less likely_ to change soon, so we deprioritize checking - in this case, check _less often_.

i.e, imagine polling for changes every 10ms:

```
// An example where the file is constantly changing.
0ms: GET /status.txt
0ms: <FIRST VALUE>
10ms: GET /status.txt
10ms: <SECOND VALUE>
20ms: GET /status.txt
20ms: <THIRD VALUE>
```

```
// An example where it is not.
0ms: GET /status.txt
0ms: <FIRST VALUE>
10ms: GET /status.txt
10ms: --- Not changed. Use ease factor of *2 when checking next time (20ms) ---
30ms: GET /status.txt
30ms: --- Not changed. Use ease factor of *2 when checking next time (40ms) ---
70ms ...
150ms...
<Until we hit a max eased value, or the maximum number of retries>
```

**Comment by nex3** [comment]
Is this something that we expect to be widely-used enough to put in `async`?

**Comment by matanlurey** [comment]
I could see it being useful (I needed a very simplified version of this for a demo, so not ready to commit it anywhere yet), especially for _mobile clients_ (read: Flutter users) that are bandwidth constrained.

You could argue it's complex enough to go in it's own package, but it depends what the mission of this package is - a collection of useful async utilities or just a tightly curated "mass demand" library. Either works for me.

**Comment by nex3** [comment]
> it depends what the mission of this package is - a collection of useful async utilities or just a tightly curated "mass demand" library

I'd say it's for utilities that are broadly useful and pretty fundamental—things that make good building blocks for more complex use-cases. That's a subjective line, but I think all good API design has a lot of subjectivity :smile:.

For `backoff()`, I totally buy that it's useful when doing expensive polling. The crux of the question for me is, how often is polling likely to be the best solution, as opposed to a push-based model of some sort? My intuition is that in most Flutter/web cases, the user will have some control over the server, but it's possible I'm wrong.

**Comment by lrhn** [comment]
I would personally not use a `Stream` for what is essentially a timer.
I'd rather do a `Timer intervalTimer(Iterable<Duration> intervals, void callback(Timer timer))` and give you a way to create an infinite computed iterable.

You can always use a timer to feed a stream-controller if you need a stream, but the stream doesn't feel like the basic operation here.
