### ISSUE TITLE
TypeSafeStream<int> from Stream<Object> failing in Dart 1.25.0-dev.10.0

### ISSUE THREAD

**Issue by whesse** [dart-lang/async#35]
With Dart version 1.25.0-dev.10.0, some conversions from
Stream<Object> to TypeSafeStream<int> are failing.

If this is not the intent of the test, and the conversion should
succeed, it needs to be fixed in the library.

Filed a CL that fixes the test by changing some Stream<Object> to Stream<int>.

**Comment by srawlins** [comment]
I'm pretty sure this is because of https://github.com/dart-lang/sdk/issues/30339, so the tests should not have been passing earlier :)

These tests rely on re-ified types, if I'm not mistaken, so should only run in DDC or Dart 2.0 tools.

**Comment by whesse** [comment]
So the tests should be annotated so they only run in strong mode or on DDC.  There are no status files for package:test tests, so I think the annotations have to go on the tests themselves.  Until this is done, the tests will be failing on the package waterfall.

**Comment by nex3** [comment]
For reference, the failures we're seeing are of the form:

```
01:05 +833 -9: [VM] test/typed_wrapper/stream_test.dart: with valid types,
forwards where() [E]
  type 'List<Object>' is not a subtype of type 'List<int>' of 'function result'
where
    List is from dart:core
    Object is from dart:core
    Object is from dart:core
    Object is from dart:core
    List is from dart:core
    int is from dart:core
  
  package:async/src/typed/stream.dart 104:7   TypeSafeStream.toList
  test/typed_wrapper/stream_test.dart 297:44  main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                  _Completer.completeError
  package:async/src/typed/stream.dart 104:54  TypeSafeStream.toList
  ===== asynchronous gap ===========================
  dart:async                                  _asyncThenWrapperHelper
  package:async/src/typed/stream.dart 103:34  TypeSafeStream.toList
  test/typed_wrapper/stream_test.dart 297:44  main.<fn>.<fn>
```

The code throwing the error is:

```dart
  Future<List<T>> toList() async =>
      DelegatingList.typed<T>(await _stream.toList());
```

In Dart 1.0 semantics, I would expect this to ignore the type parameter on `DelegatingList.typed()` and thus return a `Future<List<dynamic>>`, which is a subtype of `Future<List<T>>`. It seems that it's instead returning a `Future<List<Object>>`, which indicates that this might be broken for real-world users. @leafpetersen, can you shed light on why this is a `List<Object>`?

**Comment by leafpetersen** [comment]
Maybe because of this:

```dart
 static List<E> typed<E>(List base) =>
      base is List<E> ? base : new TypeSafeList<E>(base);
```

On the VM, this will always return `base`, no?  Presumably here, `base` has type `List<Object>`.

**Comment by nex3** [comment]
If it's returning `base`, that means `base is List<int>` is `true`. But if that's the case, shouldn't `base` be a valid return type for `toList()`?

**Comment by leafpetersen** [comment]
We're talking about Dart 1.0, right?

> In Dart 1.0 semantics, I would expect this to ignore the type parameter on DelegatingList.typed() 

it does, so the question that is being asked at runtime is `base is List<dynamic>`, which is always true.  This test program when run on the VM prints "true":

```dart
bool foo<T>(base) {
  return base is List<T>;
}

void main() {
  print(foo<int>(<String>[]));
}
```

**Comment by nex3** [comment]
Oh, right. In that case, I guess the test is legitimately 2.0-only, since we really do want to test what happens when the underlying type is `Object`. We don't currently have a way to mark that in test, since test doesn't actually support any Dart 2.0 platforms currently, so maybe the thing to do is just to skip the test for now...
