### ISSUE TITLE
stream_test pipe uses wrong class

### ISSUE THREAD

**Issue by srawlins** [dart-lang/async#37]
stream_test `'pipe()'` has:

```dart
var consumer = new StreamController();
expect(wrapper.pipe(consumer), completes);
```

However, the variable is named consumer but constructs a StreamController.

Also, `pipe` takes a StreamConsumer.

**Comment by nex3** [comment]
This is intentional. `StreamController` (transitively) implements `StreamConsumer`, and is used here as the easiest `StreamConsumer` to construct from the core libraries.
