### ISSUE TITLE
Dartdocs and crossdart links lead to 404 pages

### ISSUE THREAD

**Issue by ddrone** [dart-lang/async#39]
Subject. Current links from https://pub.dartlang.org/packages/async for documentation and hyperlinked source lead to http://www.dartdocs.org/documentation/async/2.0.0/ and https://www.crossdart.info/p/async/2.0.0/ respectively, both of which result in 404 error.

**Comment by nex3** [comment]
This is because the dependencies are currently unresolvable--`async` depends on `test` which depends on `barback`, which causes pub to activate code that depends on `async` 1.x. There's currently no way around this until we release a version of pub that's compatible with `async` 2.0.0.

**Comment by nex3** [comment]
This is still not working, but now it's because `async` requires Dart 2.0.0 and that's not what dartdocs.org uses to build docs. I'm closing this out since there's nothing more we can do here to fix this.
