### ISSUE TITLE
Update implementations of Stream.{lastWhere, firstWhere} for Dart 2

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/async#53]
The current transitional state of `lastWhere` and `firstWhere` from lib/src/typed/stream.dart looks like this:

```dart
   Future<T> firstWhere(bool test(T element),  {Object defaultValue(), T orElse()}) =>
       _stream.firstWhere(_validateType(test), defaultValue: defaultValue ?? orElse);
```

We are deprecating (and will soon remove) the `defaultValue` argument.  So at a minimum this code needs to be updated to:

```dart
   Future<T> firstWhere(bool test(T element),  {Object defaultValue(), T orElse()}) =>
       _stream.firstWhere(_validateType(test), orElse: orElse ?? () => defaultValue());
```

Presumably at some point we will want to deprecate and remove `defaultValue` from the `TypeSafeStream` API as well.  Presumably we will need a major version bump when we remove it, since it's an API breaking change.

@nex3 would you prefer that I do this:
 - in one step 
    - remove defaultValue entirely, bump the major version
- in two steps 
  - remove the delegating use of defaultValue but leave it in the API marked deprecated
  - at some later point (possibly as part of a collected major release) remove defaultValue

**Comment by nex3** [comment]
`TypeSafeStream` isn't a public type—it's used behind-the-scenes by [`DelegatingStream.typed()`](https://www.dartdocs.org/documentation/async/1.13.3/async/DelegatingStream/typed.html) to create a casting wrapper for a given stream.

Now that `Stream.cast()` and friends exist, there's no need for `typed()` at all, in `DelegatingStream` or anywhere else in async. Probably the best thing to do is:

* Delete all the `TypeSafe*` wrappers.
* Update the static `typed()` methods to just call `cast()` on their arguments.
* Mark them as deprecated and suggest users use `cast()` directly.
* Bump the SDK constraint to whatever version first contained `cast()`.

**Comment by leafpetersen** [comment]
https://github.com/dart-lang/async/pull/54

**Comment by leafpetersen** [comment]
Landed.
