### ISSUE TITLE
Dart 2 runtime errors in tests

### ISSUE THREAD

**Issue by keertip** [dart-lang/async#57]
type '(dynamic, dynamic) => dynamic' is not a subtype of type '(_FakeTimer, _FakeTimer) => _FakeTimer' of 'combine'
dart:core                                                                         Iterable.reduce
package:fake_async/fake_async.dart 236:26                                         _minOf
package:fake_async/fake_async.dart 166:12                                         _FakeAsync._getNextTimer
package:fake_async/fake_async.dart 107:20                                         _FakeAsync.elapse
../../async/test/restartable_timer_test.dart 20:13  main.<fn>.<fn>

type '_StreamHandlerTransformer<dynamic, dynamic>' is not a subtype of type 'StreamTransformer<String, dynamic>' of 'streamTransformer' where...
type '_StreamHandlerTransformer<dynamic, dynamic>' is not a subtype of type 'StreamTransformer<String, dynamic>' of 'streamTransformer' where
  _StreamHandlerTransformer is from dart:async
  StreamTransformer is from dart:async
  String is from dart:core
dart:async                                                                   Stream.transform
../../dart/async/test/stream_group_test.dart 51:44  main.<fn>.<fn>

type 'List<Stream<dynamic>>' is not a subtype of type 'List<Stream<int>>' where...
type 'List<Stream<dynamic>>' is not a subtype of type 'List<Stream<int>>' where
  List is from dart:core
  Stream is from dart:async
  List is from dart:core
  Stream is from dart:async
  int is from dart:core
package:async/src/stream_splitter.dart 65:12                                     StreamSplitter.splitFrom
../../dart/async/test/stream_splitter_test.dart 276:35  main.<fn>

and more...

**Comment by lrhn** [comment]
`wrapper_test.dart` and `unmodifiable_collection_test.dart` are both in `package:collection`, not `package:async`, right?

**Comment by nex3** [comment]
Ah, yes, got my repos mixed up.
