### ISSUE TITLE
tests failing on Travis with -dev.61

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/async#62]
https://travis-ci.org/dart-lang/async/jobs/390861553#L531
https://travis-ci.org/dart-lang/async/jobs/390861554#L632

Very much regression.

**Comment by srawlins** [comment]
In dev.60, we landed a change to Stream and Zone onError callbacks: dart-lang/sdk@315a186#diff-3d86b3443b2ea32440e90f626168d61a

**Comment by srawlins** [comment]
CC @nex3 This is the same issue as https://github.com/dart-lang/stack_trace/issues/43.

**Comment by kevmoo** [comment]
This test `test/typed_wrapper/stream_subscription_test.dart: with invalid types, throws a CastError for onData()`

Still fails with SDK at -dev.64+

**Comment by natebosch** [comment]
These tests are passing now. Not sure if it was _only_ https://github.com/dart-lang/sdk/issues/33589 but that resolved this last issues I saw.
