### ISSUE TITLE
StreamGroup.merge([1st ,2nd]) doesn't merge the two streams. but instead returns the 2nd stream 

### ISSUE THREAD

**Issue by brilliant-ember** [dart-lang/async#70]
`Widget makeStream(){
for (int i =0 ; i <queryKeys.length; i++ ){
  Stream<QuerySnapshot> x = firestoreCollection.where("query", arrayContains:queryKeys[i]).snapshots();
   streamList.add(x);
}
 var x = StreamGroup.merge(streamList);
 return keywordSearch(x);
}
static Widget keywordSearch(Stream<QuerySnapshot> streamGroup){

  return StreamBuilder(stream: streamGroup, builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot){
                      if(!snapshot.hasData){
                        return MyLoadingWidget();
                      }
                      final int length = snapshot.data.documents.length;
                      return ListView.builder
                        itemCount: length,
                        itemBuilder: (_,int index){
                          final DocumentSnapshot doc = snapshot.data.documents[index];
                          **print(doc.data.toString());** **//(the print shows that the retrieved json is from only one stream)----**
                          return new Container(child: Text(doc.data.toString()));
                        },
                      );
                    },
  
  );`

**Comment by brilliant-ember** [comment]
this this stackoverflow tracks the issue https://stackoverflow.com/questions/51214217/combine-streams-from-firestore-in-flutter

**Comment by brilliant-ember** [comment]
Turns out that this issue also affects the RX Observable 
https://stackoverflow.com/questions/51368676/flutter-stream-builder-does-not-work-correctly-when-it-is-fed-with-observable1/52843628#52843628

**Comment by natebosch** [comment]
We have a test covering this - there is not problem in general merging two streams.

https://github.com/dart-lang/async/blob/08e8836f6d2e6b736118d92ad71138b43088e98c/test/stream_group_test.dart#L17-L34

Perhaps your stream is a broadcast Stream? Those events are explicitly not buffered and so any events that come through before you have a listener on the group's stream will be lost.

https://github.com/dart-lang/async/blob/08e8836f6d2e6b736118d92ad71138b43088e98c/test/stream_group_test.dart#L104-L116

You might find the [`SingleSubscriptionStreamTransformer`](https://pub.dartlang.org/documentation/async/latest/async/SingleSubscriptionTransformer-class.html) useful to convert a broadcast Stream to a single subscription stream and buffer events until there is a listener.

**Comment by natebosch** [comment]
> Turns out that this issue also affects the RX Observable

Note that `package:rxdart` does not depend on `package:async` and has a completely independent implementation. If there were a bug here it would not impact that package. This is another signal that the problem is coming from the input streams, not the merging.

**Comment by brilliant-ember** [comment]
Update, Observable did pass both stream contents to the function as tested with
`streamGroup.map((convert){ convert.documents.forEach((f){print(f.data["name"]);});}).listen(print);`
however the Flutter streamBuilder widget failed to update the UI with both values. 
Conclusion issue is not in the stream merging, but in displaying the content to the UI.
Thanks @natebosch  for your timely response.
