### ISSUE TITLE
valueOrCancellation should return a Future<T>

### ISSUE THREAD

**Issue by natebosch** [dart-lang/async#77]
We're using a `Completer<T>` so it should always return `Future<T>`.

With NNBD we'd either need to make the argument mandatory, or make the return type `Future<T?>`.

**Comment by TastyPi** [comment]
It already does https://github.com/dart-lang/async/blob/master/lib/src/cancelable_operation.dart#L66.

**Comment by natebosch** [comment]
Ah, we haven't published for a while.
