### ISSUE TITLE
There is a problem with the onCancel call of CancelableOperation.

### ISSUE THREAD

**Issue by CaiJingLong** [dart-lang/async#85]
example like next:

```dart
import 'package:async/async.dart';

main(List<String> arguments) async {
  var cancel = CancelableOperation.fromFuture(getNumber(), onCancel: () {
    print("on cancel");
  }).then((f) {
    print("on call method");
    var i = f();
    print("i = $i");
  });
  cancel.cancel();
  print("run end");
}

Future<int Function()> getNumber() async {
  await Future.delayed(Duration(seconds: 1));
  return () {
    print("will return 1");
    return 1;
  };
}
```

I get log 

```log
run end
```

And `onCancel`  was not called.

I delete `cancel.cancel();`, and get the log:

```log
run end

on call method

will return 1

i = 1

```

----

https://github.com/dart-lang/async/blob/1c5668ea20c919d81888ccd163f5aae585c3e016/lib/src/cancelable_operation.dart#L24-L37

I understand that onCancel should be called back synchronously when I call the cancel method. 

So what went wrong?

## Env

```bash
dart --version
Dart VM version: 2.3.0 (Fri May 3 10:32:31 2019 +0200) on "macos_x64"
```

async package version:

![image](https://user-images.githubusercontent.com/14145407/58143881-e323ab80-7c7e-11e9-8074-f2594f660d1e.png)

**Comment by natebosch** [comment]
I think you want to pass `propagateCancel = true` when you call `.then`. Alternatively you could move the `onCancel` callback to the `.then`. You're canceling the chained operation, not the original one, an cancel propagation is off by default.

https://pub.dev/documentation/async/latest/async/CancelableOperation/then.html
